services:
  db:
    image: postgres:15
    container_name: file_service_db
    environment:
      POSTGRES_DB: file_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_service_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/file_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: